version: '3'
services:
  # สร้าง container ของ expressjs โดยใช้ Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://your_username:your_password@mongodb:27017" # เมื่อเปลี่ยน username และ password ในบรรทัดที่ 30, 31 ให้เปลี่ยนตรงส่วน ^
              #  "mongodb://      ^      :      ^      @mongodb:27017" # หลังจากนั้น ให้เปลี่ยน uri ที่ index.js บรรทัด 18

  # สร้าง container ของ mongodb
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"

    # ถ้าต้องการเก็บข้อมูลไว้ต่อให้ compose ใหม่ก็ยังใช้ข้อมูลเดิมให้นำ # 2 อันล่างนี้ออก
    # volumes:
    #   - mongodb_data:/data/db

    # กำหนด Username กับ password 
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password

# ถ้าต้องการเก็บข้อมูลไว้ต่อให้ compose ใหม่ก็ยังใช้ขอมูลเดิมให้นำ # 2 อันล่างนี้ออก
# volumes:
#   mongodb_data: